routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'namespace'     => 'Web\Admin',
    'middleware'    => [ 'web' ]
], function() {

    Route::get('/admin', 'AppController@index');
});

Route::group([
    'namespace'     => 'Web\Auth',
    'middleware'    => [ 'web' ]
], function() {

    Route::get('/login/{provider}', 'AuthController@redirectToProvider')->name('login_by_provider');
    Route::get('/callback/{provider}', 'AuthController@handleProviderCallback');
});

Route::group([
    'prefix'        => LaravelLocalization::setLocale(),
    'namespace'     => 'Web\Front',
    'middleware'    => [ 'web', 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
], function() {

    Route::get( '/',  'HomeController@index')->name('home');

    Route::get( '/login',  'HomeController@index')->name('login');
    Route::get( '/register',  'HomeController@index')->name('register');
    Route::get( '/enter_email',  'HomeController@index')->name('enter_email');
    Route::get( '/enter_password',  'HomeController@index')->name('enter_password');
    Route::get( '/thank_payment',  'HomeController@index')->name('thank_payment');
    Route::get( '/error_payment',  'HomeController@index')->name('error_payment');
    Route::get( '/exist_subscription',  'HomeController@index')->name('exist_subscription');
    Route::get( '/forgot_password',  'HomeController@index')->name('forgot_password');

    Route::get('/blog',  'BlogController@index')->name('blog-main');
    Route::get('/blog/tag/{slug}',  'BlogController@tag')->name('blog-tag');
    Route::get('/blog/{category_slug}',  'BlogController@category')->name('blog-category');
    Route::get('/blog/{category_slug}/{post_slug}',  'BlogController@post')->name('blog-post');

    Route::get('/info/{slug}', 'InfoController@index')->name('info');

    Route::get( '/courses/{slug}',  'CourseController@course')->name('course');

    Route::group([
        'middleware'    => [ 'auth' ]
    ], function() {

        Route::get('/profile', 'ProfileController@index')->name('profile');
        Route::get('/checkout/{subscription_type}', 'SubscriptionController@checkout')->name('subscription.checkout');
        Route::get('/recurring/{subscription}', 'SubscriptionController@recurring')->name('subscription.recurring');

        Route::get( '/courses',  'CourseController@index')->name('courses');
    });

});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web']], function () {

    Route::group([
        'middleware'    => [ 'auth' ]
    ], function() {

        \UniSharp\LaravelFilemanager\Lfm::routes();

    });
});

Route::group([
    'namespace'     => 'Web\Front',
    'prefix'        => LaravelLocalization::setLocale(),
], function() {

    Route::get('/meetup_2', 'PresaleController@index');
    Route::get('/meetup_2/thanks', 'PresaleController@index')->name('presale.thanks');
    Route::get('/meetup_2/error', 'PresaleController@index')->name('presale.error');

    Route::post('/meetup_2/checkout', 'PresaleController@createSubscription')->name('presale.checkout');
});

app/Course.php
<?php

namespace App;

use App\Abstracts\Models\TranslatableModel;
use App\Traits\Models\Filterable;
use App\Traits\Models\Uploadable;
use Illuminate\Database\Eloquent\Builder;

class Course extends TranslatableModel
{
    use Uploadable;
    use Filterable {
        scopeFiltered as scopeFilteredTrait;
    }

    protected $table = 'course';

    public $fillable = ['price', 'banner_image', 'preview_image', 'teaser_video_code', 'banner_video_code', 'is_published', 'slug', 'season_id', 'speaker_id'];

    protected $appends = ['banner_image', 'preview_image', 'materials_count', 'lessons_materials_count', 'promo_link'];

    public $translatedAttributes = ['title', 'description', 'keywords'];

    protected $filterable_by_kw = ['title'];

    protected $casts = [
        'is_published' => 'boolean',
    ];

    public function speaker()
    {
        return $this->belongsTo(Speaker::class);
    }

    public function season()
    {
        return $this->belongsTo(Season::class);
    }

    public function lessons()
    {
        return $this->hasMany(CourseLesson::class)->orderBy('ord', 'asc');
    }

    public function materials()
    {
        return $this->hasMany(CourseLessonMaterial::class);
    }

    public function scopePublished(Builder $query) {

        $query->where($this->table . '.is_published', '=', 1);
    }

    public function setBannerImageAttribute($image)
    {
        $this->uploadedImageSet($image, 'banner_image');
    }

    public function getBannerImageAttribute()
    {
        return $this->uploadedImageGet('banner_image');
    }

    public function setPreviewImageAttribute($image)
    {
        $this->uploadedImageSet($image, 'preview_image');
    }

    public function getPreviewImageAttribute()
    {
        return $this->uploadedImageGet('preview_image');
    }

    public function getMaterialsCountAttribute()
    {
        $count_materials = $this->materials->count();

        return $count_materials + $this->lessons_materials_count;
    }

    public function getLessonsMaterialsCountAttribute()
    {
        $count_materials = 0;

        foreach ($this->lessons as $lesson) {
            $count_materials += $lesson->materials->count();
        }

        return $count_materials;
    }

    public function getPromoLinkAttribute()
    {
        $url = 'https://fast.wistia.net/embed/iframe/' . $this->teaser_video_code . '?seo=false&videoFoam=true';
        return $url;
    }

    public function getBannerLinkAttribute()
    {
        $url = 'https://fast.wistia.net/embed/iframe/' . $this->banner_video_code . '?seo=false&videoFoam=true';
        return $url;
    }

    public function scopeFiltered(Builder $query, $filters)
    {
        if (isset($filters['season_id'])){
            $query->where('season_id', $filters['season_id']);
        }
        if (isset($filters['speaker_id'])){
            $query->where('speaker_id', $filters['speaker_id']);
        }

        $this->scopeFilteredTrait($query, $filters);
    }

    public function hasAccess($user)
    {
        if ($user) {
            if ($user->active_courses->contains('id', $this->id)) {
                return true;
            }
        }
        return false;
    }
}

app/Season.php
<?php

namespace App;

use App\Abstracts\Models\TranslatableModel;
use App\Traits\Models\Filterable;
use Illuminate\Database\Eloquent\Builder;

class Season extends TranslatableModel
{
    use Filterable {
        scopeFiltered as scopeFilteredTrait;
    }

    protected $table = 'season';

    public $translatedAttributes = ['title', 'title_short'];

    protected $filterable_by_kw = ['title', 'title_short'];

    public $fillable = ['id'];

    public function courses()
    {
        return $this->hasMany(Course::class);
    }

    public function subscription_types()
    {
        return $this->belongsToMany(SubscriptionType::class, 'subscription_type_season', 'season_id', 'subscription_type_id');
    }

    public function getFirstCourseAttribute()
    {
        return $this->courses()->published()->first();
    }

    public function scopeFiltered(Builder $query, $filters)
    {
        if (isset($filters['subscription_type_id'])){
            $subscription_type_id = $filters['subscription_type_id'];
            $query->whereHas('subscription_types', function($q) use($subscription_type_id) {
                $q->where('subscription_type_id', $subscription_type_id);
            });
        }

        $this->scopeFilteredTrait($query, $filters);
    }

}

app/Http/Controllers/Api/Admin/CourseController.php
<?php

namespace App\Http\Controllers\Api\Admin;

use App\Course;
use App\Http\Controllers\Api\ApiController;
use App\Http\Requests\Admin\AdminRequest as Request;

class CourseController extends ApiController
{
    public function index(Request $request)
    {
        $query = Course::query();

        return $this->getListResponse($query, $request);
    }

    public function show(Request $request, Course $course)
    {
        return $this->getItemResponse($course, $request);
    }

    public function store(Request $request)
    {
        $course = new Course();

        $course->fill($request->except('translations_array'));

        $course->save();

        $course->fill($request->input('translations_array'));

        $course->save();

        return $this->getItemResponse($course, $request);
    }

    public function update(Request $request, Course $course)
    {
        $course->update($request->except('translations_array'));

        $course->save();

        $course->update($request->input('translations_array'));

        $course->save();

        return $this->getItemResponse($course, $request);
    }

    public function destroy(Request $request, Course $course)
    {
        $course->delete();

        return $this->getItemResponse($course, $request);
    }
}

app/Http/Controllers/Web/Front/CourseController.php
<?php

namespace App\Http\Controllers\Web\Front;

use App\Comment;
use App\CourseLesson;
use App\Http\Controllers\Web\WebController;
use function Clue\StreamFilter\fun;
use Illuminate\Http\Request;

use App\BlogPost;
use App\Season;
use App\Course;
use App\UserInfo;

class CourseController extends WebController
{
    public function index(Request $request)
    {
        $seasons = Season::query()->orderBy('created_at', 'desc')->get();

        $this->setSeoFields(trans('seo.courses.title'), trans('seo.courses.description'), trans('seo.courses.keywords'));

        return view('front.course-list', compact('seasons'));
    }

    public function course($slug)
    {
        $course = Course::where('slug', $slug)->firstOrFail();
        $seasons = Season::with('courses')->get();
        $more_courses = $course->season->courses()->published()->with('speaker')->get();
        $posts = BlogPost::with('social_count')->published()->get()->sortByDesc('social_count.view_count');

        $this->setSeoFields($course->title, $course->description, $course->keywords);

        return view('front.course-page',
            compact('course',
                'seasons',
                'more_courses',
                'posts'
            )
        );
    }

}

resources/views/front/parts/course/about_course.blade.php
<div class="about row">

    @include('front.parts.course.nav')

    <div class="about-main columns large-12 medium-12 small-12 tiny-12">

        <div class="about-main-content course_content">

            <div class="current-video">

                <div class="current_video_player" style="display:none;">
                    <div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;">
                        <div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;">
                            <iframe src="{{ $course->banner_link }}"  title="Wistia" allowtransparency="true" frameborder="0" scrolling="no"  class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="100%" height="100%"></iframe>
                        </div>
                    </div>
                </div>

                <div class="current-video-content">
                    <img src="{{ $course->banner_image['src'] }}"  alt="alt">
                    <p>{{ $course->speaker->position }}</p>
                    <button class="play-button"></button>
                    <aside>
                        <div>
                            <img src="{{ asset('images/hd1.png') }}" alt="">
                            <span>@lang('front.parts.course.about.quality')</span>
                        </div>
                        <div>
                            <img src="{{ asset('images/series1.png') }}" alt="">
                            <span>{{ $course->lessons->count() }} @lang('front.parts.course.about.series')</span>
                        </div>
                        <div>
                            <img src="{{ asset('images/mats1.png') }}" alt="">
                            <span>{{ $course->materials_count }} @lang('front.parts.course.about.materials')</span>
                        </div>
                    </aside>
                </div>
                <img src="{{ asset('images/empty.png') }}" class="gag current_lesson_preview" alt="alt">
            </div>
            @if($user && count($course->lessons))
                <div class="more-series">
                    <button class="more-button" id="show_lessons">
                        <span>@lang('front.parts.course.about.other_series')</span>
                        <i></i>
                    </button>
                </div>
            @endif
            @if($user && count($course->lessons))
                @include('front.parts.course.sidebar-mobile')
            @endif

            <div class="intro">
                <h4 class="current_lesson_title">{{ $course->title }}</h4>
                <p class="current_lesson_description">{{ $course->description }}</p>
            </div>

            @if ($user && $course->hasAccess($user) && $course->materials->count())
                <div class="materials current_lesson_materials">

                    <h4>@lang('front.parts.course.about.course_materials')</h4>

                    @foreach($course->materials as $material)

                        @if($material->size)

                            <div class="materials-item">

                                @switch($material->extension)
                                    @case('pdf')
                                        <img src="{{ asset('/images/pdf.png') }}" alt="alt">
                                    @break

                                    @case('xls')
                                        <img src="{{ asset('/images/xls.png') }}" alt="alt">
                                    @break

                                    @case('xlsx')
                                        <img src="{{ asset('/images/xls.png') }}" alt="alt">
                                    @break
                                @endswitch

                                <a href="{{ $material->file['src'] }}" target="_blank">{{ $material->title }}</a>
                                <sup>{{ $material->size }} MB</sup>

                            </div>

                        @endif

                    @endforeach

                </div>
            @endif

        </div>

        @include('front.parts.course.about_lesson')

        @if($user && count($course->lessons))
            @include('front.parts.course.sidebar')
        @endif

    </div>

</div>

resources/views/front/parts/course/about_lesson.blade.php
<div class="about-main-content lesson_content">

    <div class="current-video">

        <div class="current_video_player" style="display:none;" id="" data-start-time="0">
            <div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;">
                <div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;">
                    <iframe src=""  title="Wistia" allowtransparency="true" frameborder="0" scrolling="no"  class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="100%" height="100%"></iframe>
                </div>
            </div>
        </div>
        <div class="current-video-content">
            <img src="" alt="alt"  class=" current_lesson_preview">
            <button class="play-button"></button>
        </div>

        <img class="gag" src="{{ asset('images/empty.png') }}" alt="alt">
    </div>
    <div class="more-series">
        <button class="more-button" id="show_lessons">
            <span>@lang('front.parts.course.about.other_series')</span>
            <i></i>
        </button>
    </div>

    @include('front.parts.course.sidebar-mobile')

    <div class="intro">
        <h4 class="current_lesson_title"></h4>
        <p class="current_lesson_description"></p>
    </div>

    <div class="materials current_lesson_materials" data-materials="course">
        <h4>@lang('front.parts.course.about.course_materials')</h4>
    </div>

    <div class="materials current_lesson_materials" data-materials="lesson">
        <h4>@lang('front.parts.course.about.episode_materials')</h4>
    </div>

    <div class="comments"></div>

</div>

resources/views/front/parts/course/database.blade.php
@if(count($posts) && $user)
    <div class="database row">
        <h2>@lang('front.parts.course.database.title')</h2>
        <div class="database-wrapper">
            @foreach($posts->take(2) as $post)
                <div class="database-item">
                    <a href="{{ route('blog-post', [$post->category->slug, $post->slug]) }}" class="database-item-thumbnail">
                        <img src="{{ $post->thumbnail_image['src'] }}" alt="">
                    </a>
                    <a href="{{ route('blog-post', [$post->category->slug, $post->slug]) }}">
                        <p class="database-item-description">{{ $post->title }}</p>
                    </a>
                </div>
            @endforeach

            <a href="{{ route('blog-main') }}" class="more-materials">
                <span>@lang('front.parts.course.database.look')</span><br>
                <span>@lang('front.parts.course.database.more')</span>
                <sup>({{ $posts->count() }})</sup>
            </a>
        </div>
    </div>
@endif

resources/views/front/parts/course/more.blade.php
<div class="more row">
    <h2>@lang('front.parts.course.more.title') {{ $course->season->title_short }}</h2>
    <div class="more-wrapper">
        @foreach($more_courses->except($course->id) as $item)
            <div class="course-item">
                <a href="{{ route('course', $item->slug) }}">
                    <img src="{{ $item->preview_image['src'] }}" alt="">
                    <p class="title">{{ $item->speaker->name }}</p>
                    <p class="position">{{ $item->speaker->position }}</p>
                    <button class="play"></button>
                </a>
            </div>
        @endforeach

    </div>
</div>

resources/views/front/parts/course/nav.blade.php
<div class="about-nav columns large-12 medium-12 small-12 tiny-12">

    <div class="about-nav__dropdown">

        <button class="season" id="show_seasons">
            <span>{{ $course->season->title_short }}</span>
            <i></i>
        </button>

        {{--<ul class="other_seasons">--}}

            {{--@foreach($seasons as $season)--}}
                {{--@if($season->first_course)--}}
                    {{--<li>--}}
                        {{--<a href="{{ route('course', $season->first_course->slug) }}">{{ $season->title }}</a>--}}
                    {{--</li>--}}
                {{--@endif--}}
            {{--@endforeach--}}

        {{--</ul>--}}

    </div>

    <p class="name">{{ $course->speaker->name }}</p>

    <div class="about-nav-courselist">

        <ul>
            @foreach($more_courses as $item)
                <li class="{{ ($course->id == $item->id) ? 'active' : '' }}">
                    <a href="{{ route('course', $item->slug) }}">
                        <img src="{{ $item->speaker->avatar['src'] }}" alt="alt">
                    </a>
                </li>
            @endforeach
        </ul>

    </div>

</div>

resources/views/front/parts/course/rating.blade.php
<div class="rating">
    <h4>@lang('front.parts.course.rating.title')</h4>
    <div class="rating-slider">
        <div class="rating-slider-point"></div>
    </div>
</div>

resources/views/front/parts/course/sidebar-mobile.blade.php
<div class="about-main-sidebar about-main-sidebar-mobile">
    <div class="sidebar-list">
        @foreach($course->lessons as $lesson)
            <div class="course-item course_lesson {{ (!$lesson->hasAccess($user)) ? 'blocked' : '' }}" id="{{ $lesson->id }}">
                <img src="{{ $lesson->preview_image['src'] }}" alt="">
                <aside>
                    <button class="play">
                        <img class="unlocked" src="{{ asset('images/play.png') }}" alt="alt">

                        <img class="blocked" src="{{ asset('images/close.png') }}" alt="alt">
                    </button>
                    <p>@lang('front.parts.course.sidebar.series') {{ $loop->iteration }}: {{ $lesson->title }}</p>
                </aside>
            </div>
        @endforeach
    </div>
</div>

resources/views/front/parts/course/sidebar.blade.php
<div class="about-main-sidebar">
    <div class="sidebar-list sidebar-list-desktop">
        @foreach($course->lessons as $lesson)
            <div class="course-item course_lesson {{ (!$lesson->hasAccess($user)) ? 'blocked' : '' }}"
                 {{ (!$lesson->hasAccess($user)) ? 'data-blocked="blocked' : '' }} id="{{ $lesson->id }}">
                <img src="{{ $lesson->preview_image['src'] }}" alt="">
                <aside>
                    <button class="play">
                        <img class="unlocked" src="{{ asset('images/play.png') }}" alt="alt">
                        <img class="blocked" src="{{ asset('images/close.png') }}" alt="alt">
                    </button>
                    <p>@lang('front.parts.course.sidebar.series') {{ $loop->iteration }}: {{ $lesson->title }}</p>
                </aside>
            </div>
        @endforeach
    </div>
    <button class="btn-arrow" id="scroll_lesson">
        <img src="{{ asset('images/arrow-down.png') }}" alt="btn">
    </button>

</div>